name: Package and release
on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pacakge and release
        uses: BigWigsMods/packager@v2
